CREATE DATABASE STUDENT2;
USE STUDENT2;
CREATE TABLE STDINFO(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT ,
CITY VARCHAR(50)
);

INSERT INTO STDINFO(ROLL_NO,NAME,MARKS,CITY) VALUES(
9,"DEEPAK", 78, "DAIJI"),
(19, "NARENDRA" , 80, "GAUJI"),
(29, "SAKSHI", 100, "BAZAR"),
(39, "YOJANA" , 79, "BHANSI");

SELECT CITY, AVG(MARKS) FROM STDINFO GROUP BY CITY ORDER BY AVG(MARKS) DESC LIMIT 3; 