CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE INFO(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT
);

INSERT INTO INFO VALUES(1,"ADAM", 25000),
(2,"BOB", 30000),
(3,"CASEY", 40000);

SELECT * FROM INFO;